# Generated by Django 5.2.4 on 2026-06-07 12:35

import ckeditor.fields
import imagekit.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('excerpt', models.TextField(max_length=300, verbose_name='Résumé')),
                ('content', ckeditor.fields.RichTextField(verbose_name='Contenu')),
                ('thumbnail', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='blog/')),
                ('author_name', models.CharField(default='Équipe CFI-TECH', max_length=100, verbose_name='Auteur')),
                ('category', models.CharField(blank=True, max_length=100, verbose_name='Catégorie')),
                ('tags', models.CharField(blank=True, max_length=300, verbose_name='Tags (séparés par virgule)')),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('published', 'Publié')], default='draft', max_length=10, verbose_name='Statut')),
                ('is_featured', models.BooleanField(default=False, verbose_name='À la une')),
                ('meta_description', models.CharField(blank=True, max_length=160, verbose_name='Meta description')),
                ('views_count', models.IntegerField(default=0, verbose_name='Vues')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de publication')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Article de blog',
                'verbose_name_plural': 'Articles de blog',
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=300, verbose_name='Question')),
                ('answer', ckeditor.fields.RichTextField(verbose_name='Réponse')),
                ('category', models.CharField(choices=[('general', 'Général'), ('formation', 'Formations'), ('inscription', 'Inscription'), ('paiement', 'Paiement'), ('certificat', 'Certificats')], default='general', max_length=20, verbose_name='Catégorie')),
                ('display_order', models.IntegerField(default=0, verbose_name='Ordre')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQ',
                'ordering': ['category', 'display_order'],
            },
        ),
        migrations.CreateModel(
            name='GalleryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Titre')),
                ('media_type', models.CharField(choices=[('photo', 'Photo'), ('video', 'Vidéo')], default='photo', max_length=10, verbose_name='Type')),
                ('image', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='gallery/')),
                ('video_url', models.URLField(blank=True, verbose_name='URL Vidéo YouTube/Vimeo')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('event_name', models.CharField(blank=True, max_length=150, verbose_name='Événement')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('display_order', models.IntegerField(default=0, verbose_name='Ordre')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Élément galerie',
                'verbose_name_plural': 'Galerie',
                'ordering': ['display_order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NewsletterSubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('full_name', models.CharField(blank=True, max_length=100, verbose_name='Nom complet')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('subscribed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Abonné Newsletter',
                'verbose_name_plural': 'Abonnés Newsletter',
                'ordering': ['-subscribed_at'],
            },
        ),
        migrations.CreateModel(
            name='NoorEnergyService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Titre')),
                ('icon', models.CharField(choices=[('solar-panel', '☀️ Énergie Solaire'), ('zap', '⚡ Électricité'), ('home', '🏠 Bâtiment'), ('wind', '💨 Climatisation'), ('activity', '📊 Audit'), ('tool', '🔧 Maintenance')], default='zap', max_length=30, verbose_name='Icône')),
                ('description', models.TextField(verbose_name='Description')),
                ('image', models.ImageField(blank=True, null=True, upload_to='noor_energy/', verbose_name='Image')),
                ('display_order', models.IntegerField(default=0, verbose_name='Ordre')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
            ],
            options={
                'verbose_name': 'Service Noor Energy',
                'verbose_name_plural': 'Services Noor Energy',
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nom du partenaire')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('logo', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='partners/')),
                ('partner_type', models.CharField(choices=[('strategique', 'Partenaire Stratégique'), ('technique', 'Partenaire Technique'), ('academique', 'Partenaire Académique'), ('commercial', 'Partenaire Commercial'), ('institutionnel', 'Partenaire Institutionnel')], default='strategique', max_length=20, verbose_name='Type')),
                ('description', ckeditor.fields.RichTextField(blank=True, verbose_name='Description')),
                ('services', models.TextField(blank=True, verbose_name='Services offerts')),
                ('website_url', models.URLField(blank=True, verbose_name='Site web')),
                ('facebook_url', models.URLField(blank=True, verbose_name='Facebook')),
                ('linkedin_url', models.URLField(blank=True, verbose_name='LinkedIn')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Mise en avant')),
                ('is_noor_energy', models.BooleanField(default=False, verbose_name='Noor Energy')),
                ('display_order', models.IntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Partenaire',
                'verbose_name_plural': 'Partenaires',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SiteConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='CFI-TECH', max_length=100, verbose_name='Nom du site')),
                ('slogan', models.CharField(default='Apprenez, Innovez, Réussissez avec CFI-TECH', max_length=200, verbose_name='Slogan')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='branding/', verbose_name='Logo')),
                ('banderole', models.ImageField(blank=True, null=True, upload_to='branding/', verbose_name='Banderole hero')),
                ('phone', models.CharField(default='+223 78 78 73 39', max_length=30, verbose_name='Téléphone')),
                ('whatsapp', models.CharField(default='+22378787339', max_length=30, verbose_name='WhatsApp')),
                ('email', models.EmailField(default='cfitech3@gmail.com', max_length=254, verbose_name='Email')),
                ('address', models.TextField(default='Moussabougou, près du marché, descente du 3e pont, Bamako, Mali', verbose_name='Adresse')),
                ('google_maps_embed', models.TextField(blank=True, verbose_name='Google Maps Embed URL')),
                ('facebook_url', models.URLField(blank=True, verbose_name='Facebook')),
                ('instagram_url', models.URLField(blank=True, verbose_name='Instagram')),
                ('linkedin_url', models.URLField(blank=True, verbose_name='LinkedIn')),
                ('youtube_url', models.URLField(blank=True, verbose_name='YouTube')),
                ('twitter_url', models.URLField(blank=True, verbose_name='Twitter/X')),
                ('tiktok_url', models.URLField(blank=True, verbose_name='TikTok')),
                ('meta_description', models.TextField(blank=True, default="CFI-TECH - Centre de Formation et d'Innovation Technologique à Bamako, Mali. Formations en informatique, programmation, cybersécurité, IA, énergie solaire.", max_length=160, verbose_name='Meta description SEO')),
                ('google_analytics_id', models.CharField(blank=True, max_length=50, verbose_name='Google Analytics ID')),
                ('stat_etudiants', models.IntegerField(default=500, verbose_name='Étudiants formés')),
                ('stat_reussite', models.IntegerField(default=95, verbose_name='Taux de réussite (%)')),
                ('stat_formations', models.IntegerField(default=20, verbose_name='Formations')),
                ('stat_certifications', models.IntegerField(default=300, verbose_name='Certifications délivrées')),
            ],
            options={
                'verbose_name': 'Configuration du site',
                'verbose_name_plural': 'Configuration du site',
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='Nom complet')),
                ('job_title', models.CharField(max_length=100, verbose_name='Poste')),
                ('bio', models.TextField(blank=True, verbose_name='Biographie')),
                ('photo', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='team/')),
                ('linkedin_url', models.URLField(blank=True, verbose_name='LinkedIn')),
                ('speciality', models.CharField(blank=True, max_length=200, verbose_name='Spécialité')),
                ('display_order', models.IntegerField(default=0, verbose_name='Ordre')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
            ],
            options={
                'verbose_name': 'Membre équipe',
                'verbose_name_plural': "Membres de l'équipe",
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='Nom complet')),
                ('job_title', models.CharField(blank=True, max_length=100, verbose_name='Titre / Poste')),
                ('photo', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='testimonials/')),
                ('message', models.TextField(verbose_name='Témoignage')),
                ('rating', models.IntegerField(choices=[(1, '1 étoile(s)'), (2, '2 étoile(s)'), (3, '3 étoile(s)'), (4, '4 étoile(s)'), (5, '5 étoile(s)')], default=5, verbose_name='Note')),
                ('formation_suivie', models.CharField(blank=True, max_length=150, verbose_name='Formation suivie')),
                ('is_featured', models.BooleanField(default=False, verbose_name='À la une')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Témoignage',
                'verbose_name_plural': 'Témoignages',
                'ordering': ['-is_featured', '-created_at'],
            },
        ),
    ]
