# Generated by Django 5.2.4 on 2026-06-18 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_contactmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='address',
            field=models.CharField(blank=True, max_length=300, verbose_name='Adresse'),
        ),
        migrations.AddField(
            model_name='partner',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='partner',
            name='instagram_url',
            field=models.URLField(blank=True, verbose_name='Instagram'),
        ),
        migrations.AddField(
            model_name='partner',
            name='phone',
            field=models.CharField(blank=True, max_length=30, verbose_name='Téléphone'),
        ),
        migrations.AddField(
            model_name='partner',
            name='slogan',
            field=models.CharField(blank=True, max_length=200, verbose_name='Slogan'),
        ),
        migrations.AddField(
            model_name='partner',
            name='tiktok_url',
            field=models.URLField(blank=True, verbose_name='TikTok'),
        ),
        migrations.AddField(
            model_name='partner',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=30, verbose_name='WhatsApp'),
        ),
        migrations.AddField(
            model_name='partner',
            name='youtube_url',
            field=models.URLField(blank=True, verbose_name='YouTube'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='partners/', verbose_name='Logo'),
        ),
    ]
