# Generated by Django 5.2.4 on 2026-06-07 12:35

import ckeditor.fields
import imagekit.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Titre du service')),
                ('icon', models.CharField(choices=[('monitor', '🖥️ Installation informatique'), ('tool', '🔧 Maintenance'), ('wifi', '📶 Réseau & Sécurité'), ('globe', '🌐 Développement Web'), ('smartphone', '📱 Développement Mobile'), ('shopping-bag', '🛍️ Vente matériels'), ('briefcase', '💼 Conseil IT'), ('trending-up', '📈 Consulting Digital'), ('headphones', '🎧 Support Technique')], default='monitor', max_length=30, verbose_name='Icône')),
                ('short_description', models.CharField(max_length=200, verbose_name='Description courte')),
                ('description', ckeditor.fields.RichTextField(blank=True, verbose_name='Description complète')),
                ('image', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='services/')),
                ('features', models.TextField(blank=True, verbose_name='Fonctionnalités (une par ligne)')),
                ('price_info', models.CharField(blank=True, max_length=200, verbose_name='Info tarif')),
                ('cta_text', models.CharField(default='Demander un devis', max_length=50, verbose_name='Texte bouton CTA')),
                ('display_order', models.IntegerField(default=0, verbose_name='Ordre')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Mis en avant')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'ordering': ['display_order'],
            },
        ),
    ]
