# Generated by Django 5.2.4 on 2026-06-13 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logiciel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom du logiciel')),
                ('category', models.CharField(choices=[('bureautique', 'Bureautique'), ('comptabilite', 'Comptabilité'), ('gestion', 'Gestion'), ('securite', 'Sécurité'), ('developpement', 'Développement'), ('design', 'Design & Création'), ('reseau', 'Réseau & Système'), ('autre', 'Autre')], default='bureautique', max_length=20, verbose_name='Catégorie')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logiciels/', verbose_name='Logo')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('version', models.CharField(blank=True, max_length=50, verbose_name='Version')),
                ('editor', models.CharField(blank=True, max_length=100, verbose_name='Éditeur')),
                ('website_url', models.URLField(blank=True, verbose_name='Site officiel')),
                ('is_free', models.BooleanField(default=False, verbose_name='Gratuit / Open source')),
                ('price_info', models.CharField(blank=True, max_length=200, verbose_name='Info tarif')),
                ('is_formation', models.BooleanField(default=True, verbose_name='Utilisé en formation')),
                ('is_sale', models.BooleanField(default=False, verbose_name='Disponible à la vente')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Mis en avant')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('display_order', models.IntegerField(default=0, verbose_name='Ordre')),
            ],
            options={
                'verbose_name': 'Logiciel',
                'verbose_name_plural': 'Logiciels',
                'ordering': ['display_order', 'name'],
            },
        ),
    ]
