# Generated by Django 5.2.4 on 2026-06-07 12:35

import ckeditor.fields
import django.db.models.deletion
import imagekit.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nom du domaine')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('icon', models.CharField(choices=[('monitor', 'Informatique générale'), ('code', 'Programmation'), ('globe', 'Développement Web'), ('wifi', 'Réseau'), ('shield', 'Cybersécurité'), ('cpu', 'Intelligence Artificielle'), ('file-text', 'Bureautique'), ('zap', 'Électricité'), ('sun', 'Énergie Solaire'), ('package', 'Logistique'), ('trending-up', 'Comptabilité'), ('bar-chart', 'Marketing'), ('message-square', 'Anglais'), ('star', 'Développement Personnel'), ('settings', 'Autres')], default='monitor', max_length=30, verbose_name='Icône')),
                ('color', models.CharField(default='#1565C0', max_length=7, verbose_name='Couleur accent (hex)')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('display_order', models.IntegerField(default=0, verbose_name='Ordre')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
            ],
            options={
                'verbose_name': 'Domaine',
                'verbose_name_plural': 'Domaines de formation',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='Nom complet')),
                ('title', models.CharField(max_length=150, verbose_name='Titre / Expertise')),
                ('bio', models.TextField(blank=True, verbose_name='Biographie')),
                ('photo', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='trainers/')),
                ('linkedin_url', models.URLField(blank=True, verbose_name='LinkedIn')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email professionnel')),
                ('years_experience', models.IntegerField(default=0, verbose_name="Années d'expérience")),
                ('certifications', models.TextField(blank=True, verbose_name='Certifications')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
            ],
            options={
                'verbose_name': 'Formateur',
                'verbose_name_plural': 'Formateurs',
            },
        ),
        migrations.CreateModel(
            name='Formation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre de la formation')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('subtitle', models.CharField(blank=True, max_length=200, verbose_name='Sous-titre')),
                ('description', ckeditor.fields.RichTextField(verbose_name='Description complète')),
                ('excerpt', models.TextField(max_length=300, verbose_name='Résumé court')),
                ('affiche', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='formations/affiches/', verbose_name='Affiche (1024x1024)')),
                ('level', models.CharField(choices=[('debutant', 'Débutant'), ('intermediaire', 'Intermédiaire'), ('avance', 'Avancé'), ('tous', 'Tous niveaux')], default='tous', max_length=20, verbose_name='Niveau')),
                ('mode', models.CharField(choices=[('presentiel', 'Présentiel'), ('distance', 'À distance'), ('hybride', 'Hybride')], default='presentiel', max_length=20, verbose_name='Mode')),
                ('duration', models.CharField(max_length=100, verbose_name='Durée (ex: 3 mois, 40h)')),
                ('schedule', models.CharField(blank=True, help_text='Ex: Lun/Mer/Ven 18h-20h', max_length=200, verbose_name='Horaires')),
                ('status', models.CharField(choices=[('coming_soon', 'Bientôt disponible'), ('open', 'Inscriptions ouvertes'), ('full', 'Complet'), ('ongoing', 'En cours'), ('finished', 'Terminé')], default='coming_soon', max_length=20, verbose_name='Statut')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Date de début')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Date de fin')),
                ('registration_deadline', models.DateField(blank=True, null=True, verbose_name="Date limite d'inscription")),
                ('total_spots', models.IntegerField(default=30, verbose_name='Places totales')),
                ('registered_count', models.IntegerField(default=0, verbose_name='Inscrits')),
                ('price', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='Prix (FCFA)')),
                ('price_note', models.CharField(blank=True, help_text='Ex: Facilités de paiement disponibles', max_length=200, verbose_name='Note sur le prix')),
                ('is_free', models.BooleanField(default=False, verbose_name='Formation gratuite')),
                ('program', ckeditor.fields.RichTextField(blank=True, verbose_name='Programme / Contenu')),
                ('prerequisites', models.TextField(blank=True, verbose_name='Prérequis')),
                ('objectives', models.TextField(blank=True, verbose_name='Objectifs')),
                ('certification', models.CharField(blank=True, max_length=200, verbose_name='Certification délivrée')),
                ('meta_description', models.CharField(blank=True, max_length=160, verbose_name='Meta description')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Formation à la une')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('views_count', models.IntegerField(default=0, verbose_name='Vues')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('domain', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='formations', to='formations.domain', verbose_name='Domaine')),
                ('trainer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='formations', to='formations.trainer', verbose_name='Formateur')),
            ],
            options={
                'verbose_name': 'Formation',
                'verbose_name_plural': 'Formations',
                'ordering': ['-is_featured', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Inscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=100, verbose_name='Nom')),
                ('first_name', models.CharField(max_length=100, verbose_name='Prénom')),
                ('phone', models.CharField(max_length=30, verbose_name='Téléphone')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('address', models.CharField(blank=True, max_length=200, verbose_name='Adresse / Quartier')),
                ('level', models.CharField(choices=[('aucun', 'Aucun'), ('primaire', 'Primaire'), ('college', 'Collège'), ('lycee', 'Lycée'), ('bac', 'Baccalauréat'), ('licence', 'Licence / BTS'), ('master', 'Master / Ingénieur'), ('doctorat', 'Doctorat'), ('professionnel', 'Professionnel')], default='lycee', max_length=20, verbose_name="Niveau d'études")),
                ('message', models.TextField(blank=True, verbose_name='Message / Questions')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('confirmed', 'Confirmé'), ('cancelled', 'Annulé'), ('completed', 'Terminé')], default='pending', max_length=20, verbose_name='Statut')),
                ('reference', models.CharField(blank=True, max_length=20, unique=True, verbose_name='Référence')),
                ('notes_admin', models.TextField(blank=True, verbose_name='Notes administrateur')),
                ('synced_to_sheets', models.BooleanField(default=False, verbose_name='Synchronisé Google Sheets')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('formation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inscriptions', to='formations.formation', verbose_name='Formation')),
            ],
            options={
                'verbose_name': 'Inscription',
                'verbose_name_plural': 'Inscriptions',
                'ordering': ['-created_at'],
            },
        ),
    ]
